spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/laboratorymanagement?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 12345678
  thymeleaf:
    mode: HTML5
    encoding: utf-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    static-path-pattern: /static/**
